### ISSUE TITLE
Critical bug with TheChopper

### ISSUE THREAD

**Issue by leagris** [estebes/Gravitation-Suite-Reloaded#7]
```
[19:27:27] [Server thread/ERROR] [FML/]: Unable to determine registrant mod for com.estebes.gravisuitereloaded.item.tool.ItemToolTheChopper@30946a01. This is a critical error and should be impossible
java.lang.Throwable
        at cpw.mods.fml.common.eventhandler.EventBus.register(EventBus.java:55) [EventBus.class:?]
        at com.estebes.gravisuitereloaded.item.tool.ItemToolTheChopper.<init>(ItemToolTheChopper.java:35) [ItemToolTheChopper.class:?]
        at com.estebes.gravisuitereloaded.init.ItemInit.<clinit>(ItemInit.java:23) [ItemInit.class:?]
        at java.lang.Class.forName0(Native Method) [?:1.8.0_74]
        at java.lang.Class.forName(Class.java:348) [?:1.8.0_74]
        at cpw.mods.fml.common.registry.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:70) [ObjectHolderRegistry.class:?]
        at cpw.mods.fml.common.registry.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:39) [ObjectHolderRegistry.class:?]
        at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:554) [Loader.class:?]
        at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88) [FMLServerHandler.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

**Comment by estebes** [comment]
this in theory is does not break anything. it is related to how i instantiate items iirc.
